"""empty message

Revision ID: 0a49b89fac73
Revises: 0af8b8813a5c
Create Date: 2016-01-05 17:20:27.125074

"""

# revision identifiers, used by Alembic.
revision = '0a49b89fac73'
down_revision = '0af8b8813a5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
