"""empty message

Revision ID: 58a773e7b396
Revises: 0a49b89fac73
Create Date: 2016-01-07 12:09:25.059723

"""

# revision identifiers, used by Alembic.
revision = '58a773e7b396'
down_revision = '0a49b89fac73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.add_column(u'roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column(u'roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.add_column(u'users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column(u'users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column(u'users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'name')
    op.drop_column(u'users', 'member_since')
    op.drop_column(u'users', 'location')
    op.drop_column(u'users', 'last_seen')
    op.drop_column(u'users', 'avatar_hash')
    op.drop_column(u'users', 'about_me')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column(u'roles', 'permissions')
    op.drop_column(u'roles', 'default')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    ### end Alembic commands ###
